CREATE TABLE [dbo].[Comunas]
(
	[Id] INT NOT NULL CONSTRAINT [PK_Comunas] PRIMARY KEY IDENTITY(1,1),
	[Nombre] NVARCHAR(250) NOT NULL,
	[Codigo] NVARCHAR(5) NOT NULL,
	[RegionId] INT NOT NULL CONSTRAINT [FK_Comuna_Region] FOREIGN KEY REFERENCES [dbo].[Regiones](ID)
)
