CREATE TABLE [dbo].[Comunas]
(
	[Id] INT NOT NULL CONSTRAINT [PK_Comunas] PRIMARY KEY,
	[Nombre] NVARCHAR(250) NOT NULL,
	[RegionId] INT NOT NULL CONSTRAINT [FK_Comuna_Region] FOREIGN KEY REFERENCES [dbo].[Regiones](Id)
)
